name: inspr
description: Best of Inspirational and Motivational quotes
publish_to: "none" # Remove this to publish to pub.dev
version: 2.0.13+26

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: 5.0.6595
  http: ^0.13.4
  provider: ^6.0.2
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.0.2
  path: ^1.8.1
  flutter_slidable: ^1.2.0
  flutter_local_notifications: ^9.4.0
  launch_review: ^3.0.1
  intro_views_flutter: ^3.2.0
  cached_network_image: ^3.2.0
  image_picker: ^0.8.5
  flutter_colorpicker: ^1.0.3
  share_plus: ^4.0.4
  package_info_plus: ^4.1.0
  flutter_share_me: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/main.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: LatoLight
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: LatoBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Bold.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: SpecialElite
      fonts:
        - asset: assets/fonts/SpecialElite-Regular.ttf
